---
baseline_timezone: "UTC"
baseline_ntp_servers: []
baseline_admin_users: []
baseline_sudo_nopasswd: false
baseline_disable_root_ssh_login: true
baseline_disable_ssh_password_auth: false
baseline_firewall_extra_services: []
baseline_enable_dnf_automatic: true
